#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SVD")]
	public partial class SVDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDB_VehicleTheftLocation(DB_VehicleTheftLocation instance);
    partial void UpdateDB_VehicleTheftLocation(DB_VehicleTheftLocation instance);
    partial void DeleteDB_VehicleTheftLocation(DB_VehicleTheftLocation instance);
    partial void InsertDB_TheftMethod(DB_TheftMethod instance);
    partial void UpdateDB_TheftMethod(DB_TheftMethod instance);
    partial void DeleteDB_TheftMethod(DB_TheftMethod instance);
    partial void InsertDB_Colour(DB_Colour instance);
    partial void UpdateDB_Colour(DB_Colour instance);
    partial void DeleteDB_Colour(DB_Colour instance);
    partial void InsertDB_VehicleSecurityType(DB_VehicleSecurityType instance);
    partial void UpdateDB_VehicleSecurityType(DB_VehicleSecurityType instance);
    partial void DeleteDB_VehicleSecurityType(DB_VehicleSecurityType instance);
    partial void InsertDB_VehiclePhoto(DB_VehiclePhoto instance);
    partial void UpdateDB_VehiclePhoto(DB_VehiclePhoto instance);
    partial void DeleteDB_VehiclePhoto(DB_VehiclePhoto instance);
    partial void InsertDB_VehicleVideo(DB_VehicleVideo instance);
    partial void UpdateDB_VehicleVideo(DB_VehicleVideo instance);
    partial void DeleteDB_VehicleVideo(DB_VehicleVideo instance);
    partial void InsertDB_VehicleSecurity(DB_VehicleSecurity instance);
    partial void UpdateDB_VehicleSecurity(DB_VehicleSecurity instance);
    partial void DeleteDB_VehicleSecurity(DB_VehicleSecurity instance);
    partial void InsertDB_Location(DB_Location instance);
    partial void UpdateDB_Location(DB_Location instance);
    partial void DeleteDB_Location(DB_Location instance);
    partial void InsertDB_Vehicle(DB_Vehicle instance);
    partial void UpdateDB_Vehicle(DB_Vehicle instance);
    partial void DeleteDB_Vehicle(DB_Vehicle instance);
    #endregion
		
		public SVDDataContext() : 
				base(global::SVD.Properties.Settings.Default.SVDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SVDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SVDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SVDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SVDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DB_VehicleTheftLocation> DB_VehicleTheftLocations
		{
			get
			{
				return this.GetTable<DB_VehicleTheftLocation>();
			}
		}
		
		public System.Data.Linq.Table<DB_TheftMethod> DB_TheftMethods
		{
			get
			{
				return this.GetTable<DB_TheftMethod>();
			}
		}
		
		public System.Data.Linq.Table<DB_Colour> DB_Colours
		{
			get
			{
				return this.GetTable<DB_Colour>();
			}
		}
		
		public System.Data.Linq.Table<DB_VehicleSecurityType> DB_VehicleSecurityTypes
		{
			get
			{
				return this.GetTable<DB_VehicleSecurityType>();
			}
		}
		
		public System.Data.Linq.Table<DB_VehiclePhoto> DB_VehiclePhotos
		{
			get
			{
				return this.GetTable<DB_VehiclePhoto>();
			}
		}
		
		public System.Data.Linq.Table<DB_VehicleVideo> DB_VehicleVideos
		{
			get
			{
				return this.GetTable<DB_VehicleVideo>();
			}
		}
		
		public System.Data.Linq.Table<DB_VehicleSecurity> DB_VehicleSecurities
		{
			get
			{
				return this.GetTable<DB_VehicleSecurity>();
			}
		}
		
		public System.Data.Linq.Table<DB_Location> DB_Locations
		{
			get
			{
				return this.GetTable<DB_Location>();
			}
		}
		
		public System.Data.Linq.Table<DB_Vehicle> DB_Vehicles
		{
			get
			{
				return this.GetTable<DB_Vehicle>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetColourStatistic")]
		public ISingleResult<GetColourStatisticResult> GetColourStatistic([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<GetColourStatisticResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTheftMethodStatistic")]
		public ISingleResult<GetTheftMethodStatisticResult> GetTheftMethodStatistic([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<GetTheftMethodStatisticResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetManufacturerStatistic")]
		public ISingleResult<GetManufacturerStatisticResult> GetManufacturerStatistic([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<GetManufacturerStatisticResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetModelStatistic")]
		public ISingleResult<GetModelStatisticResult> GetModelStatistic([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<GetModelStatisticResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetVehicleSecurityTypeStatistic")]
		public ISingleResult<GetVehicleSecurityTypeStatisticResult> GetVehicleSecurityTypeStatistic([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<GetVehicleSecurityTypeStatisticResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCountryStatistic")]
		public ISingleResult<GetCountryStatisticResult> GetCountryStatistic([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<GetCountryStatisticResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetArea1Statistic")]
		public ISingleResult<GetArea1StatisticResult> GetArea1Statistic([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<GetArea1StatisticResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetArea2Statistic")]
		public ISingleResult<GetArea2StatisticResult> GetArea2Statistic([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<GetArea2StatisticResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetLocalityStatistic")]
		public ISingleResult<GetLocalityStatisticResult> GetLocalityStatistic([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<GetLocalityStatisticResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRouteStatistic")]
		public ISingleResult<GetRouteStatisticResult> GetRouteStatistic([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<GetRouteStatisticResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSubLocalityStatistic")]
		public ISingleResult<GetSubLocalityStatisticResult> GetSubLocalityStatistic([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<GetSubLocalityStatisticResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VehicleLocations")]
	public partial class DB_VehicleTheftLocation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VehicleID;
		
		private int _LocationID;
		
		private EntityRef<DB_Location> _DB_Location;
		
		private EntityRef<DB_Vehicle> _DB_Vehicle;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVehicleIDChanging(int value);
    partial void OnVehicleIDChanged();
    partial void OnLocationIDChanging(int value);
    partial void OnLocationIDChanged();
    #endregion
		
		public DB_VehicleTheftLocation()
		{
			this._DB_Location = default(EntityRef<DB_Location>);
			this._DB_Vehicle = default(EntityRef<DB_Vehicle>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int VehicleID
		{
			get
			{
				return this._VehicleID;
			}
			set
			{
				if ((this._VehicleID != value))
				{
					if (this._DB_Vehicle.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVehicleIDChanging(value);
					this.SendPropertyChanging();
					this._VehicleID = value;
					this.SendPropertyChanged("VehicleID");
					this.OnVehicleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					if (this._DB_Location.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLocationIDChanging(value);
					this.SendPropertyChanging();
					this._LocationID = value;
					this.SendPropertyChanged("LocationID");
					this.OnLocationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_Location_DB_VehicleTheftLocation", Storage="_DB_Location", ThisKey="LocationID", OtherKey="ID", IsForeignKey=true)]
		public DB_Location DB_Location
		{
			get
			{
				return this._DB_Location.Entity;
			}
			set
			{
				DB_Location previousValue = this._DB_Location.Entity;
				if (((previousValue != value) 
							|| (this._DB_Location.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DB_Location.Entity = null;
						previousValue.DB_VehicleTheftLocations.Remove(this);
					}
					this._DB_Location.Entity = value;
					if ((value != null))
					{
						value.DB_VehicleTheftLocations.Add(this);
						this._LocationID = value.ID;
					}
					else
					{
						this._LocationID = default(int);
					}
					this.SendPropertyChanged("DB_Location");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_Vehicle_DB_VehicleTheftLocation", Storage="_DB_Vehicle", ThisKey="VehicleID", OtherKey="ID", IsForeignKey=true)]
		public DB_Vehicle DB_Vehicle
		{
			get
			{
				return this._DB_Vehicle.Entity;
			}
			set
			{
				DB_Vehicle previousValue = this._DB_Vehicle.Entity;
				if (((previousValue != value) 
							|| (this._DB_Vehicle.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DB_Vehicle.Entity = null;
						previousValue.DB_VehicleTheftLocations.Remove(this);
					}
					this._DB_Vehicle.Entity = value;
					if ((value != null))
					{
						value.DB_VehicleTheftLocations.Add(this);
						this._VehicleID = value.ID;
					}
					else
					{
						this._VehicleID = default(int);
					}
					this.SendPropertyChanged("DB_Vehicle");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheftMethods")]
	public partial class DB_TheftMethod : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private EntitySet<DB_Vehicle> _DB_Vehicles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public DB_TheftMethod()
		{
			this._DB_Vehicles = new EntitySet<DB_Vehicle>(new Action<DB_Vehicle>(this.attach_DB_Vehicles), new Action<DB_Vehicle>(this.detach_DB_Vehicles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_TheftMethod_DB_Vehicle", Storage="_DB_Vehicles", ThisKey="ID", OtherKey="TheftMethodID")]
		public EntitySet<DB_Vehicle> DB_Vehicles
		{
			get
			{
				return this._DB_Vehicles;
			}
			set
			{
				this._DB_Vehicles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DB_Vehicles(DB_Vehicle entity)
		{
			this.SendPropertyChanging();
			entity.DB_TheftMethod = this;
		}
		
		private void detach_DB_Vehicles(DB_Vehicle entity)
		{
			this.SendPropertyChanging();
			entity.DB_TheftMethod = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Colours")]
	public partial class DB_Colour : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private EntitySet<DB_Vehicle> _DB_Vehicles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public DB_Colour()
		{
			this._DB_Vehicles = new EntitySet<DB_Vehicle>(new Action<DB_Vehicle>(this.attach_DB_Vehicles), new Action<DB_Vehicle>(this.detach_DB_Vehicles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_Colour_DB_Vehicle", Storage="_DB_Vehicles", ThisKey="ID", OtherKey="ColourID")]
		public EntitySet<DB_Vehicle> DB_Vehicles
		{
			get
			{
				return this._DB_Vehicles;
			}
			set
			{
				this._DB_Vehicles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DB_Vehicles(DB_Vehicle entity)
		{
			this.SendPropertyChanging();
			entity.DB_Colour = this;
		}
		
		private void detach_DB_Vehicles(DB_Vehicle entity)
		{
			this.SendPropertyChanging();
			entity.DB_Colour = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VehicleSecurityTypes")]
	public partial class DB_VehicleSecurityType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private EntitySet<DB_VehicleSecurity> _DB_VehicleSecurities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public DB_VehicleSecurityType()
		{
			this._DB_VehicleSecurities = new EntitySet<DB_VehicleSecurity>(new Action<DB_VehicleSecurity>(this.attach_DB_VehicleSecurities), new Action<DB_VehicleSecurity>(this.detach_DB_VehicleSecurities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_VehicleSecurityType_DB_VehicleSecurity", Storage="_DB_VehicleSecurities", ThisKey="ID", OtherKey="TypeID")]
		public EntitySet<DB_VehicleSecurity> DB_VehicleSecurities
		{
			get
			{
				return this._DB_VehicleSecurities;
			}
			set
			{
				this._DB_VehicleSecurities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DB_VehicleSecurities(DB_VehicleSecurity entity)
		{
			this.SendPropertyChanging();
			entity.DB_VehicleSecurityType = this;
		}
		
		private void detach_DB_VehicleSecurities(DB_VehicleSecurity entity)
		{
			this.SendPropertyChanging();
			entity.DB_VehicleSecurityType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VehiclePhotos")]
	public partial class DB_VehiclePhoto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _VehicleID;
		
		private string _Filename;
		
		private string _Comment;
		
		private System.DateTime _DateModified;
		
		private System.DateTime _DateCreated;
		
		private byte _PhotoType;
		
		private EntityRef<DB_Vehicle> _DB_Vehicle;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnVehicleIDChanging(int value);
    partial void OnVehicleIDChanged();
    partial void OnFilenameChanging(string value);
    partial void OnFilenameChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnDateModifiedChanging(System.DateTime value);
    partial void OnDateModifiedChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnPhotoTypeChanging(byte value);
    partial void OnPhotoTypeChanged();
    #endregion
		
		public DB_VehiclePhoto()
		{
			this._DB_Vehicle = default(EntityRef<DB_Vehicle>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleID", DbType="Int NOT NULL")]
		public int VehicleID
		{
			get
			{
				return this._VehicleID;
			}
			set
			{
				if ((this._VehicleID != value))
				{
					if (this._DB_Vehicle.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVehicleIDChanging(value);
					this.SendPropertyChanging();
					this._VehicleID = value;
					this.SendPropertyChanged("VehicleID");
					this.OnVehicleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filename", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Filename
		{
			get
			{
				return this._Filename;
			}
			set
			{
				if ((this._Filename != value))
				{
					this.OnFilenameChanging(value);
					this.SendPropertyChanging();
					this._Filename = value;
					this.SendPropertyChanged("Filename");
					this.OnFilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(1000)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime NOT NULL")]
		public System.DateTime DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this.OnDateModifiedChanging(value);
					this.SendPropertyChanging();
					this._DateModified = value;
					this.SendPropertyChanged("DateModified");
					this.OnDateModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoType", DbType="TinyInt NOT NULL")]
		public byte PhotoType
		{
			get
			{
				return this._PhotoType;
			}
			set
			{
				if ((this._PhotoType != value))
				{
					this.OnPhotoTypeChanging(value);
					this.SendPropertyChanging();
					this._PhotoType = value;
					this.SendPropertyChanged("PhotoType");
					this.OnPhotoTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_Vehicle_DB_VehiclePhoto", Storage="_DB_Vehicle", ThisKey="VehicleID", OtherKey="ID", IsForeignKey=true)]
		public DB_Vehicle DB_Vehicle
		{
			get
			{
				return this._DB_Vehicle.Entity;
			}
			set
			{
				DB_Vehicle previousValue = this._DB_Vehicle.Entity;
				if (((previousValue != value) 
							|| (this._DB_Vehicle.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DB_Vehicle.Entity = null;
						previousValue.DB_VehiclePhotos.Remove(this);
					}
					this._DB_Vehicle.Entity = value;
					if ((value != null))
					{
						value.DB_VehiclePhotos.Add(this);
						this._VehicleID = value.ID;
					}
					else
					{
						this._VehicleID = default(int);
					}
					this.SendPropertyChanged("DB_Vehicle");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VehicleVideos")]
	public partial class DB_VehicleVideo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _VehicleID;
		
		private string _Url;
		
		private string _Comment;
		
		private EntityRef<DB_Vehicle> _DB_Vehicle;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnVehicleIDChanging(int value);
    partial void OnVehicleIDChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    #endregion
		
		public DB_VehicleVideo()
		{
			this._DB_Vehicle = default(EntityRef<DB_Vehicle>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleID", DbType="Int NOT NULL")]
		public int VehicleID
		{
			get
			{
				return this._VehicleID;
			}
			set
			{
				if ((this._VehicleID != value))
				{
					if (this._DB_Vehicle.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVehicleIDChanging(value);
					this.SendPropertyChanging();
					this._VehicleID = value;
					this.SendPropertyChanged("VehicleID");
					this.OnVehicleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(1000)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_Vehicle_DB_VehicleVideo", Storage="_DB_Vehicle", ThisKey="VehicleID", OtherKey="ID", IsForeignKey=true)]
		public DB_Vehicle DB_Vehicle
		{
			get
			{
				return this._DB_Vehicle.Entity;
			}
			set
			{
				DB_Vehicle previousValue = this._DB_Vehicle.Entity;
				if (((previousValue != value) 
							|| (this._DB_Vehicle.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DB_Vehicle.Entity = null;
						previousValue.DB_VehicleVideos.Remove(this);
					}
					this._DB_Vehicle.Entity = value;
					if ((value != null))
					{
						value.DB_VehicleVideos.Add(this);
						this._VehicleID = value.ID;
					}
					else
					{
						this._VehicleID = default(int);
					}
					this.SendPropertyChanged("DB_Vehicle");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VehicleSecurity")]
	public partial class DB_VehicleSecurity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _VehicleID;
		
		private int _TypeID;
		
		private EntityRef<DB_VehicleSecurityType> _DB_VehicleSecurityType;
		
		private EntityRef<DB_Vehicle> _DB_Vehicle;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnVehicleIDChanging(int value);
    partial void OnVehicleIDChanged();
    partial void OnTypeIDChanging(int value);
    partial void OnTypeIDChanged();
    #endregion
		
		public DB_VehicleSecurity()
		{
			this._DB_VehicleSecurityType = default(EntityRef<DB_VehicleSecurityType>);
			this._DB_Vehicle = default(EntityRef<DB_Vehicle>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleID", DbType="Int NOT NULL")]
		public int VehicleID
		{
			get
			{
				return this._VehicleID;
			}
			set
			{
				if ((this._VehicleID != value))
				{
					if (this._DB_Vehicle.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVehicleIDChanging(value);
					this.SendPropertyChanging();
					this._VehicleID = value;
					this.SendPropertyChanged("VehicleID");
					this.OnVehicleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeID", DbType="Int NOT NULL")]
		public int TypeID
		{
			get
			{
				return this._TypeID;
			}
			set
			{
				if ((this._TypeID != value))
				{
					if (this._DB_VehicleSecurityType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTypeIDChanging(value);
					this.SendPropertyChanging();
					this._TypeID = value;
					this.SendPropertyChanged("TypeID");
					this.OnTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_VehicleSecurityType_DB_VehicleSecurity", Storage="_DB_VehicleSecurityType", ThisKey="TypeID", OtherKey="ID", IsForeignKey=true)]
		public DB_VehicleSecurityType DB_VehicleSecurityType
		{
			get
			{
				return this._DB_VehicleSecurityType.Entity;
			}
			set
			{
				DB_VehicleSecurityType previousValue = this._DB_VehicleSecurityType.Entity;
				if (((previousValue != value) 
							|| (this._DB_VehicleSecurityType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DB_VehicleSecurityType.Entity = null;
						previousValue.DB_VehicleSecurities.Remove(this);
					}
					this._DB_VehicleSecurityType.Entity = value;
					if ((value != null))
					{
						value.DB_VehicleSecurities.Add(this);
						this._TypeID = value.ID;
					}
					else
					{
						this._TypeID = default(int);
					}
					this.SendPropertyChanged("DB_VehicleSecurityType");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_Vehicle_DB_VehicleSecurity", Storage="_DB_Vehicle", ThisKey="VehicleID", OtherKey="ID", IsForeignKey=true)]
		public DB_Vehicle DB_Vehicle
		{
			get
			{
				return this._DB_Vehicle.Entity;
			}
			set
			{
				DB_Vehicle previousValue = this._DB_Vehicle.Entity;
				if (((previousValue != value) 
							|| (this._DB_Vehicle.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DB_Vehicle.Entity = null;
						previousValue.DB_VehicleSecurities.Remove(this);
					}
					this._DB_Vehicle.Entity = value;
					if ((value != null))
					{
						value.DB_VehicleSecurities.Add(this);
						this._VehicleID = value.ID;
					}
					else
					{
						this._VehicleID = default(int);
					}
					this.SendPropertyChanged("DB_Vehicle");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Locations")]
	public partial class DB_Location : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _Code;
		
		private byte _Type;
		
		private System.Nullable<double> _Latitude;
		
		private System.Nullable<double> _Longitude;
		
		private System.Nullable<int> _ParentLocationId;
		
		private EntitySet<DB_VehicleTheftLocation> _DB_VehicleTheftLocations;
		
		private EntitySet<DB_Location> _DB_Locations;
		
		private EntityRef<DB_Location> _Location1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnTypeChanging(byte value);
    partial void OnTypeChanged();
    partial void OnLatitudeChanging(System.Nullable<double> value);
    partial void OnLatitudeChanged();
    partial void OnLongitudeChanging(System.Nullable<double> value);
    partial void OnLongitudeChanged();
    partial void OnParentLocationIdChanging(System.Nullable<int> value);
    partial void OnParentLocationIdChanged();
    #endregion
		
		public DB_Location()
		{
			this._DB_VehicleTheftLocations = new EntitySet<DB_VehicleTheftLocation>(new Action<DB_VehicleTheftLocation>(this.attach_DB_VehicleTheftLocations), new Action<DB_VehicleTheftLocation>(this.detach_DB_VehicleTheftLocations));
			this._DB_Locations = new EntitySet<DB_Location>(new Action<DB_Location>(this.attach_DB_Locations), new Action<DB_Location>(this.detach_DB_Locations));
			this._Location1 = default(EntityRef<DB_Location>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="TinyInt NOT NULL")]
		public byte Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Float")]
		public System.Nullable<double> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Float")]
		public System.Nullable<double> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentLocationId", DbType="Int")]
		public System.Nullable<int> ParentLocationId
		{
			get
			{
				return this._ParentLocationId;
			}
			set
			{
				if ((this._ParentLocationId != value))
				{
					if (this._Location1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnParentLocationIdChanging(value);
					this.SendPropertyChanging();
					this._ParentLocationId = value;
					this.SendPropertyChanged("ParentLocationId");
					this.OnParentLocationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_Location_DB_VehicleTheftLocation", Storage="_DB_VehicleTheftLocations", ThisKey="ID", OtherKey="LocationID")]
		public EntitySet<DB_VehicleTheftLocation> DB_VehicleTheftLocations
		{
			get
			{
				return this._DB_VehicleTheftLocations;
			}
			set
			{
				this._DB_VehicleTheftLocations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_Location_DB_Location", Storage="_DB_Locations", ThisKey="ID", OtherKey="ParentLocationId")]
		public EntitySet<DB_Location> DB_Locations
		{
			get
			{
				return this._DB_Locations;
			}
			set
			{
				this._DB_Locations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_Location_DB_Location", Storage="_Location1", ThisKey="ParentLocationId", OtherKey="ID", IsForeignKey=true)]
		public DB_Location Location1
		{
			get
			{
				return this._Location1.Entity;
			}
			set
			{
				DB_Location previousValue = this._Location1.Entity;
				if (((previousValue != value) 
							|| (this._Location1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Location1.Entity = null;
						previousValue.DB_Locations.Remove(this);
					}
					this._Location1.Entity = value;
					if ((value != null))
					{
						value.DB_Locations.Add(this);
						this._ParentLocationId = value.ID;
					}
					else
					{
						this._ParentLocationId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Location1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DB_VehicleTheftLocations(DB_VehicleTheftLocation entity)
		{
			this.SendPropertyChanging();
			entity.DB_Location = this;
		}
		
		private void detach_DB_VehicleTheftLocations(DB_VehicleTheftLocation entity)
		{
			this.SendPropertyChanging();
			entity.DB_Location = null;
		}
		
		private void attach_DB_Locations(DB_Location entity)
		{
			this.SendPropertyChanging();
			entity.Location1 = this;
		}
		
		private void detach_DB_Locations(DB_Location entity)
		{
			this.SendPropertyChanging();
			entity.Location1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vehicles")]
	public partial class DB_Vehicle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Guid _MemberUID;
		
		private int _ManufacturerID;
		
		private int _ModelID;
		
		private int _VehicleTypeId;
		
		private System.Nullable<int> _ColourID;
		
		private System.Nullable<int> _Year;
		
		private string _Registration;
		
		private string _VIN;
		
		private string _EngineNumber;
		
		private string _Description;
		
		private string _PoliceForce;
		
		private string _PolicePhoneNo;
		
		private string _PoliceReference;
		
		private string _TheftDescription;
		
		private System.Nullable<decimal> _TheftLongitude;
		
		private System.Nullable<decimal> _TheftLatitude;
		
		private System.Nullable<bool> _IsLocationApprox;
		
		private System.Nullable<System.DateTime> _TheftDate;
		
		private System.Nullable<int> _TheftMethodID;
		
		private System.DateTime _DateModified;
		
		private System.DateTime _DateCreated;
		
		private byte _Status;
		
		private EntitySet<DB_VehicleTheftLocation> _DB_VehicleTheftLocations;
		
		private EntitySet<DB_VehiclePhoto> _DB_VehiclePhotos;
		
		private EntitySet<DB_VehicleVideo> _DB_VehicleVideos;
		
		private EntitySet<DB_VehicleSecurity> _DB_VehicleSecurities;
		
		private EntityRef<DB_Colour> _DB_Colour;
		
		private EntityRef<DB_TheftMethod> _DB_TheftMethod;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMemberUIDChanging(System.Guid value);
    partial void OnMemberUIDChanged();
    partial void OnManufacturerIDChanging(int value);
    partial void OnManufacturerIDChanged();
    partial void OnModelIDChanging(int value);
    partial void OnModelIDChanged();
    partial void OnVehicleTypeIdChanging(int value);
    partial void OnVehicleTypeIdChanged();
    partial void OnColourIDChanging(System.Nullable<int> value);
    partial void OnColourIDChanged();
    partial void OnYearChanging(System.Nullable<int> value);
    partial void OnYearChanged();
    partial void OnRegistrationChanging(string value);
    partial void OnRegistrationChanged();
    partial void OnVINChanging(string value);
    partial void OnVINChanged();
    partial void OnEngineNumberChanging(string value);
    partial void OnEngineNumberChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnPoliceForceChanging(string value);
    partial void OnPoliceForceChanged();
    partial void OnPolicePhoneNoChanging(string value);
    partial void OnPolicePhoneNoChanged();
    partial void OnPoliceReferenceChanging(string value);
    partial void OnPoliceReferenceChanged();
    partial void OnTheftDescriptionChanging(string value);
    partial void OnTheftDescriptionChanged();
    partial void OnTheftLongitudeChanging(System.Nullable<decimal> value);
    partial void OnTheftLongitudeChanged();
    partial void OnTheftLatitudeChanging(System.Nullable<decimal> value);
    partial void OnTheftLatitudeChanged();
    partial void OnIsLocationApproxChanging(System.Nullable<bool> value);
    partial void OnIsLocationApproxChanged();
    partial void OnTheftDateChanging(System.Nullable<System.DateTime> value);
    partial void OnTheftDateChanged();
    partial void OnTheftMethodIDChanging(System.Nullable<int> value);
    partial void OnTheftMethodIDChanged();
    partial void OnDateModifiedChanging(System.DateTime value);
    partial void OnDateModifiedChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnStatusChanging(byte value);
    partial void OnStatusChanged();
    #endregion
		
		public DB_Vehicle()
		{
			this._DB_VehicleTheftLocations = new EntitySet<DB_VehicleTheftLocation>(new Action<DB_VehicleTheftLocation>(this.attach_DB_VehicleTheftLocations), new Action<DB_VehicleTheftLocation>(this.detach_DB_VehicleTheftLocations));
			this._DB_VehiclePhotos = new EntitySet<DB_VehiclePhoto>(new Action<DB_VehiclePhoto>(this.attach_DB_VehiclePhotos), new Action<DB_VehiclePhoto>(this.detach_DB_VehiclePhotos));
			this._DB_VehicleVideos = new EntitySet<DB_VehicleVideo>(new Action<DB_VehicleVideo>(this.attach_DB_VehicleVideos), new Action<DB_VehicleVideo>(this.detach_DB_VehicleVideos));
			this._DB_VehicleSecurities = new EntitySet<DB_VehicleSecurity>(new Action<DB_VehicleSecurity>(this.attach_DB_VehicleSecurities), new Action<DB_VehicleSecurity>(this.detach_DB_VehicleSecurities));
			this._DB_Colour = default(EntityRef<DB_Colour>);
			this._DB_TheftMethod = default(EntityRef<DB_TheftMethod>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberUID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid MemberUID
		{
			get
			{
				return this._MemberUID;
			}
			set
			{
				if ((this._MemberUID != value))
				{
					this.OnMemberUIDChanging(value);
					this.SendPropertyChanging();
					this._MemberUID = value;
					this.SendPropertyChanged("MemberUID");
					this.OnMemberUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManufacturerID", DbType="Int NOT NULL")]
		public int ManufacturerID
		{
			get
			{
				return this._ManufacturerID;
			}
			set
			{
				if ((this._ManufacturerID != value))
				{
					this.OnManufacturerIDChanging(value);
					this.SendPropertyChanging();
					this._ManufacturerID = value;
					this.SendPropertyChanged("ManufacturerID");
					this.OnManufacturerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelID", DbType="Int NOT NULL")]
		public int ModelID
		{
			get
			{
				return this._ModelID;
			}
			set
			{
				if ((this._ModelID != value))
				{
					this.OnModelIDChanging(value);
					this.SendPropertyChanging();
					this._ModelID = value;
					this.SendPropertyChanged("ModelID");
					this.OnModelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleTypeId", DbType="Int NOT NULL")]
		public int VehicleTypeId
		{
			get
			{
				return this._VehicleTypeId;
			}
			set
			{
				if ((this._VehicleTypeId != value))
				{
					this.OnVehicleTypeIdChanging(value);
					this.SendPropertyChanging();
					this._VehicleTypeId = value;
					this.SendPropertyChanged("VehicleTypeId");
					this.OnVehicleTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColourID", DbType="Int")]
		public System.Nullable<int> ColourID
		{
			get
			{
				return this._ColourID;
			}
			set
			{
				if ((this._ColourID != value))
				{
					if (this._DB_Colour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnColourIDChanging(value);
					this.SendPropertyChanging();
					this._ColourID = value;
					this.SendPropertyChanged("ColourID");
					this.OnColourIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registration", DbType="VarChar(50)")]
		public string Registration
		{
			get
			{
				return this._Registration;
			}
			set
			{
				if ((this._Registration != value))
				{
					this.OnRegistrationChanging(value);
					this.SendPropertyChanging();
					this._Registration = value;
					this.SendPropertyChanged("Registration");
					this.OnRegistrationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIN", DbType="Char(17)")]
		public string VIN
		{
			get
			{
				return this._VIN;
			}
			set
			{
				if ((this._VIN != value))
				{
					this.OnVINChanging(value);
					this.SendPropertyChanging();
					this._VIN = value;
					this.SendPropertyChanged("VIN");
					this.OnVINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngineNumber", DbType="Char(17)")]
		public string EngineNumber
		{
			get
			{
				return this._EngineNumber;
			}
			set
			{
				if ((this._EngineNumber != value))
				{
					this.OnEngineNumberChanging(value);
					this.SendPropertyChanging();
					this._EngineNumber = value;
					this.SendPropertyChanged("EngineNumber");
					this.OnEngineNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoliceForce", DbType="VarChar(255)")]
		public string PoliceForce
		{
			get
			{
				return this._PoliceForce;
			}
			set
			{
				if ((this._PoliceForce != value))
				{
					this.OnPoliceForceChanging(value);
					this.SendPropertyChanging();
					this._PoliceForce = value;
					this.SendPropertyChanged("PoliceForce");
					this.OnPoliceForceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicePhoneNo", DbType="VarChar(20)")]
		public string PolicePhoneNo
		{
			get
			{
				return this._PolicePhoneNo;
			}
			set
			{
				if ((this._PolicePhoneNo != value))
				{
					this.OnPolicePhoneNoChanging(value);
					this.SendPropertyChanging();
					this._PolicePhoneNo = value;
					this.SendPropertyChanged("PolicePhoneNo");
					this.OnPolicePhoneNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoliceReference", DbType="VarChar(255)")]
		public string PoliceReference
		{
			get
			{
				return this._PoliceReference;
			}
			set
			{
				if ((this._PoliceReference != value))
				{
					this.OnPoliceReferenceChanging(value);
					this.SendPropertyChanging();
					this._PoliceReference = value;
					this.SendPropertyChanged("PoliceReference");
					this.OnPoliceReferenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheftDescription", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string TheftDescription
		{
			get
			{
				return this._TheftDescription;
			}
			set
			{
				if ((this._TheftDescription != value))
				{
					this.OnTheftDescriptionChanging(value);
					this.SendPropertyChanging();
					this._TheftDescription = value;
					this.SendPropertyChanged("TheftDescription");
					this.OnTheftDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheftLongitude", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> TheftLongitude
		{
			get
			{
				return this._TheftLongitude;
			}
			set
			{
				if ((this._TheftLongitude != value))
				{
					this.OnTheftLongitudeChanging(value);
					this.SendPropertyChanging();
					this._TheftLongitude = value;
					this.SendPropertyChanged("TheftLongitude");
					this.OnTheftLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheftLatitude", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> TheftLatitude
		{
			get
			{
				return this._TheftLatitude;
			}
			set
			{
				if ((this._TheftLatitude != value))
				{
					this.OnTheftLatitudeChanging(value);
					this.SendPropertyChanging();
					this._TheftLatitude = value;
					this.SendPropertyChanged("TheftLatitude");
					this.OnTheftLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLocationApprox", DbType="Bit")]
		public System.Nullable<bool> IsLocationApprox
		{
			get
			{
				return this._IsLocationApprox;
			}
			set
			{
				if ((this._IsLocationApprox != value))
				{
					this.OnIsLocationApproxChanging(value);
					this.SendPropertyChanging();
					this._IsLocationApprox = value;
					this.SendPropertyChanged("IsLocationApprox");
					this.OnIsLocationApproxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheftDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> TheftDate
		{
			get
			{
				return this._TheftDate;
			}
			set
			{
				if ((this._TheftDate != value))
				{
					this.OnTheftDateChanging(value);
					this.SendPropertyChanging();
					this._TheftDate = value;
					this.SendPropertyChanged("TheftDate");
					this.OnTheftDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheftMethodID", DbType="Int")]
		public System.Nullable<int> TheftMethodID
		{
			get
			{
				return this._TheftMethodID;
			}
			set
			{
				if ((this._TheftMethodID != value))
				{
					if (this._DB_TheftMethod.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTheftMethodIDChanging(value);
					this.SendPropertyChanging();
					this._TheftMethodID = value;
					this.SendPropertyChanged("TheftMethodID");
					this.OnTheftMethodIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime NOT NULL")]
		public System.DateTime DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this.OnDateModifiedChanging(value);
					this.SendPropertyChanging();
					this._DateModified = value;
					this.SendPropertyChanged("DateModified");
					this.OnDateModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="TinyInt NOT NULL")]
		public byte Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_Vehicle_DB_VehicleTheftLocation", Storage="_DB_VehicleTheftLocations", ThisKey="ID", OtherKey="VehicleID")]
		public EntitySet<DB_VehicleTheftLocation> DB_VehicleTheftLocations
		{
			get
			{
				return this._DB_VehicleTheftLocations;
			}
			set
			{
				this._DB_VehicleTheftLocations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_Vehicle_DB_VehiclePhoto", Storage="_DB_VehiclePhotos", ThisKey="ID", OtherKey="VehicleID")]
		public EntitySet<DB_VehiclePhoto> DB_VehiclePhotos
		{
			get
			{
				return this._DB_VehiclePhotos;
			}
			set
			{
				this._DB_VehiclePhotos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_Vehicle_DB_VehicleVideo", Storage="_DB_VehicleVideos", ThisKey="ID", OtherKey="VehicleID")]
		public EntitySet<DB_VehicleVideo> DB_VehicleVideos
		{
			get
			{
				return this._DB_VehicleVideos;
			}
			set
			{
				this._DB_VehicleVideos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_Vehicle_DB_VehicleSecurity", Storage="_DB_VehicleSecurities", ThisKey="ID", OtherKey="VehicleID")]
		public EntitySet<DB_VehicleSecurity> DB_VehicleSecurities
		{
			get
			{
				return this._DB_VehicleSecurities;
			}
			set
			{
				this._DB_VehicleSecurities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_Colour_DB_Vehicle", Storage="_DB_Colour", ThisKey="ColourID", OtherKey="ID", IsForeignKey=true)]
		public DB_Colour DB_Colour
		{
			get
			{
				return this._DB_Colour.Entity;
			}
			set
			{
				DB_Colour previousValue = this._DB_Colour.Entity;
				if (((previousValue != value) 
							|| (this._DB_Colour.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DB_Colour.Entity = null;
						previousValue.DB_Vehicles.Remove(this);
					}
					this._DB_Colour.Entity = value;
					if ((value != null))
					{
						value.DB_Vehicles.Add(this);
						this._ColourID = value.ID;
					}
					else
					{
						this._ColourID = default(Nullable<int>);
					}
					this.SendPropertyChanged("DB_Colour");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DB_TheftMethod_DB_Vehicle", Storage="_DB_TheftMethod", ThisKey="TheftMethodID", OtherKey="ID", IsForeignKey=true)]
		public DB_TheftMethod DB_TheftMethod
		{
			get
			{
				return this._DB_TheftMethod.Entity;
			}
			set
			{
				DB_TheftMethod previousValue = this._DB_TheftMethod.Entity;
				if (((previousValue != value) 
							|| (this._DB_TheftMethod.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DB_TheftMethod.Entity = null;
						previousValue.DB_Vehicles.Remove(this);
					}
					this._DB_TheftMethod.Entity = value;
					if ((value != null))
					{
						value.DB_Vehicles.Add(this);
						this._TheftMethodID = value.ID;
					}
					else
					{
						this._TheftMethodID = default(Nullable<int>);
					}
					this.SendPropertyChanged("DB_TheftMethod");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DB_VehicleTheftLocations(DB_VehicleTheftLocation entity)
		{
			this.SendPropertyChanging();
			entity.DB_Vehicle = this;
		}
		
		private void detach_DB_VehicleTheftLocations(DB_VehicleTheftLocation entity)
		{
			this.SendPropertyChanging();
			entity.DB_Vehicle = null;
		}
		
		private void attach_DB_VehiclePhotos(DB_VehiclePhoto entity)
		{
			this.SendPropertyChanging();
			entity.DB_Vehicle = this;
		}
		
		private void detach_DB_VehiclePhotos(DB_VehiclePhoto entity)
		{
			this.SendPropertyChanging();
			entity.DB_Vehicle = null;
		}
		
		private void attach_DB_VehicleVideos(DB_VehicleVideo entity)
		{
			this.SendPropertyChanging();
			entity.DB_Vehicle = this;
		}
		
		private void detach_DB_VehicleVideos(DB_VehicleVideo entity)
		{
			this.SendPropertyChanging();
			entity.DB_Vehicle = null;
		}
		
		private void attach_DB_VehicleSecurities(DB_VehicleSecurity entity)
		{
			this.SendPropertyChanging();
			entity.DB_Vehicle = this;
		}
		
		private void detach_DB_VehicleSecurities(DB_VehicleSecurity entity)
		{
			this.SendPropertyChanging();
			entity.DB_Vehicle = null;
		}
	}
	
	public partial class GetColourStatisticResult
	{
		
		private System.Nullable<int> _ColourID;
		
		private System.Nullable<int> _Instances;
		
		private System.Nullable<long> _Rank;
		
		public GetColourStatisticResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColourID", DbType="Int")]
		public System.Nullable<int> ColourID
		{
			get
			{
				return this._ColourID;
			}
			set
			{
				if ((this._ColourID != value))
				{
					this._ColourID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instances", DbType="Int")]
		public System.Nullable<int> Instances
		{
			get
			{
				return this._Instances;
			}
			set
			{
				if ((this._Instances != value))
				{
					this._Instances = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="BigInt")]
		public System.Nullable<long> Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this._Rank = value;
				}
			}
		}
	}
	
	public partial class GetTheftMethodStatisticResult
	{
		
		private System.Nullable<int> _TheftMethodID;
		
		private System.Nullable<int> _Instances;
		
		private System.Nullable<long> _Rank;
		
		public GetTheftMethodStatisticResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheftMethodID", DbType="Int")]
		public System.Nullable<int> TheftMethodID
		{
			get
			{
				return this._TheftMethodID;
			}
			set
			{
				if ((this._TheftMethodID != value))
				{
					this._TheftMethodID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instances", DbType="Int")]
		public System.Nullable<int> Instances
		{
			get
			{
				return this._Instances;
			}
			set
			{
				if ((this._Instances != value))
				{
					this._Instances = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="BigInt")]
		public System.Nullable<long> Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this._Rank = value;
				}
			}
		}
	}
	
	public partial class GetManufacturerStatisticResult
	{
		
		private int _ManufacturerID;
		
		private System.Nullable<int> _Instances;
		
		private System.Nullable<long> _Rank;
		
		public GetManufacturerStatisticResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManufacturerID", DbType="Int NOT NULL")]
		public int ManufacturerID
		{
			get
			{
				return this._ManufacturerID;
			}
			set
			{
				if ((this._ManufacturerID != value))
				{
					this._ManufacturerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instances", DbType="Int")]
		public System.Nullable<int> Instances
		{
			get
			{
				return this._Instances;
			}
			set
			{
				if ((this._Instances != value))
				{
					this._Instances = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="BigInt")]
		public System.Nullable<long> Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this._Rank = value;
				}
			}
		}
	}
	
	public partial class GetModelStatisticResult
	{
		
		private int _ModelID;
		
		private System.Nullable<int> _Instances;
		
		private System.Nullable<long> _Rank;
		
		public GetModelStatisticResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelID", DbType="Int NOT NULL")]
		public int ModelID
		{
			get
			{
				return this._ModelID;
			}
			set
			{
				if ((this._ModelID != value))
				{
					this._ModelID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instances", DbType="Int")]
		public System.Nullable<int> Instances
		{
			get
			{
				return this._Instances;
			}
			set
			{
				if ((this._Instances != value))
				{
					this._Instances = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="BigInt")]
		public System.Nullable<long> Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this._Rank = value;
				}
			}
		}
	}
	
	public partial class GetVehicleSecurityTypeStatisticResult
	{
		
		private int _TypeID;
		
		private System.Nullable<int> _Instances;
		
		private System.Nullable<long> _Rank;
		
		public GetVehicleSecurityTypeStatisticResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeID", DbType="Int NOT NULL")]
		public int TypeID
		{
			get
			{
				return this._TypeID;
			}
			set
			{
				if ((this._TypeID != value))
				{
					this._TypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instances", DbType="Int")]
		public System.Nullable<int> Instances
		{
			get
			{
				return this._Instances;
			}
			set
			{
				if ((this._Instances != value))
				{
					this._Instances = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="BigInt")]
		public System.Nullable<long> Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this._Rank = value;
				}
			}
		}
	}
	
	public partial class GetCountryStatisticResult
	{
		
		private int _LocationID;
		
		private System.Nullable<int> _Instances;
		
		private System.Nullable<long> _Rank;
		
		public GetCountryStatisticResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", DbType="Int NOT NULL")]
		public int LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					this._LocationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instances", DbType="Int")]
		public System.Nullable<int> Instances
		{
			get
			{
				return this._Instances;
			}
			set
			{
				if ((this._Instances != value))
				{
					this._Instances = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="BigInt")]
		public System.Nullable<long> Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this._Rank = value;
				}
			}
		}
	}
	
	public partial class GetArea1StatisticResult
	{
		
		private int _LocationID;
		
		private System.Nullable<int> _Instances;
		
		private System.Nullable<long> _Rank;
		
		public GetArea1StatisticResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", DbType="Int NOT NULL")]
		public int LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					this._LocationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instances", DbType="Int")]
		public System.Nullable<int> Instances
		{
			get
			{
				return this._Instances;
			}
			set
			{
				if ((this._Instances != value))
				{
					this._Instances = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="BigInt")]
		public System.Nullable<long> Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this._Rank = value;
				}
			}
		}
	}
	
	public partial class GetArea2StatisticResult
	{
		
		private int _LocationID;
		
		private System.Nullable<int> _Instances;
		
		private System.Nullable<long> _Rank;
		
		public GetArea2StatisticResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", DbType="Int NOT NULL")]
		public int LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					this._LocationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instances", DbType="Int")]
		public System.Nullable<int> Instances
		{
			get
			{
				return this._Instances;
			}
			set
			{
				if ((this._Instances != value))
				{
					this._Instances = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="BigInt")]
		public System.Nullable<long> Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this._Rank = value;
				}
			}
		}
	}
	
	public partial class GetLocalityStatisticResult
	{
		
		private int _LocationID;
		
		private System.Nullable<int> _Instances;
		
		private System.Nullable<long> _Rank;
		
		public GetLocalityStatisticResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", DbType="Int NOT NULL")]
		public int LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					this._LocationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instances", DbType="Int")]
		public System.Nullable<int> Instances
		{
			get
			{
				return this._Instances;
			}
			set
			{
				if ((this._Instances != value))
				{
					this._Instances = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="BigInt")]
		public System.Nullable<long> Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this._Rank = value;
				}
			}
		}
	}
	
	public partial class GetRouteStatisticResult
	{
		
		private int _LocationID;
		
		private System.Nullable<int> _Instances;
		
		private System.Nullable<long> _Rank;
		
		public GetRouteStatisticResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", DbType="Int NOT NULL")]
		public int LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					this._LocationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instances", DbType="Int")]
		public System.Nullable<int> Instances
		{
			get
			{
				return this._Instances;
			}
			set
			{
				if ((this._Instances != value))
				{
					this._Instances = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="BigInt")]
		public System.Nullable<long> Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this._Rank = value;
				}
			}
		}
	}
	
	public partial class GetSubLocalityStatisticResult
	{
		
		private int _LocationID;
		
		private System.Nullable<int> _Instances;
		
		private System.Nullable<long> _Rank;
		
		public GetSubLocalityStatisticResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", DbType="Int NOT NULL")]
		public int LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					this._LocationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instances", DbType="Int")]
		public System.Nullable<int> Instances
		{
			get
			{
				return this._Instances;
			}
			set
			{
				if ((this._Instances != value))
				{
					this._Instances = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="BigInt")]
		public System.Nullable<long> Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this._Rank = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
