//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVD.VDWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Responses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.GetVehicleManufacturersResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.GetVehicleManufacturerResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.GetVehicleModelResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.GetVehicleModelsByManufacturerResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.GetVehicleModelsByManufacturerIdResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.UpdateVehicleTypeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.UpdateVehicleManufacturerResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.UpdateVehicleModelResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.UpdateClientResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.DeleteVehicleTypeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.DeleteVehicleModelResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.DeleteClientResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.GetVehicleTypesResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetVehicleManufacturersResponse", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Responses")]
    [System.SerializableAttribute()]
    public partial class GetVehicleManufacturersResponse : SVD.VDWS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SVD.VDWS.VehicleManufacturer> ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.GetOperationResultType ResultTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SVD.VDWS.VehicleManufacturer> Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.GetOperationResultType ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetVehicleManufacturerResponse", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Responses")]
    [System.SerializableAttribute()]
    public partial class GetVehicleManufacturerResponse : SVD.VDWS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.VehicleManufacturer ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.GetOperationResultType ResultTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.VehicleManufacturer Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.GetOperationResultType ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetVehicleModelResponse", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Responses")]
    [System.SerializableAttribute()]
    public partial class GetVehicleModelResponse : SVD.VDWS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.VehicleModel ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.GetOperationResultType ResultTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.VehicleModel Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.GetOperationResultType ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetVehicleModelsByManufacturerResponse", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Responses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.GetVehicleModelsByManufacturerIdResponse))]
    public partial class GetVehicleModelsByManufacturerResponse : SVD.VDWS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SVD.VDWS.VehicleModel> ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.GetOperationResultType ResultTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SVD.VDWS.VehicleModel> Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.GetOperationResultType ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetVehicleModelsByManufacturerIdResponse", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Responses")]
    [System.SerializableAttribute()]
    public partial class GetVehicleModelsByManufacturerIdResponse : SVD.VDWS.GetVehicleModelsByManufacturerResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateVehicleTypeResponse", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Responses")]
    [System.SerializableAttribute()]
    public partial class UpdateVehicleTypeResponse : SVD.VDWS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.UpdateOperationResultType ResultTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.UpdateOperationResultType ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateVehicleManufacturerResponse", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Responses")]
    [System.SerializableAttribute()]
    public partial class UpdateVehicleManufacturerResponse : SVD.VDWS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.UpdateOperationResultType ResultTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.UpdateOperationResultType ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateVehicleModelResponse", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Responses")]
    [System.SerializableAttribute()]
    public partial class UpdateVehicleModelResponse : SVD.VDWS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.UpdateOperationResultType ResultTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.UpdateOperationResultType ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateClientResponse", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Responses")]
    [System.SerializableAttribute()]
    public partial class UpdateClientResponse : SVD.VDWS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.UpdateOperationResultType ResultTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.UpdateOperationResultType ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteVehicleTypeResponse", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Responses")]
    [System.SerializableAttribute()]
    public partial class DeleteVehicleTypeResponse : SVD.VDWS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.DeleteOperationResultType ResultTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.DeleteOperationResultType ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteVehicleModelResponse", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Responses")]
    [System.SerializableAttribute()]
    public partial class DeleteVehicleModelResponse : SVD.VDWS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.DeleteOperationResultType ResultTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.DeleteOperationResultType ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteClientResponse", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Responses")]
    [System.SerializableAttribute()]
    public partial class DeleteClientResponse : SVD.VDWS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.DeleteOperationResultType ResultTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.DeleteOperationResultType ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetVehicleTypesResponse", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Responses")]
    [System.SerializableAttribute()]
    public partial class GetVehicleTypesResponse : SVD.VDWS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SVD.VDWS.VehicleType> ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.GetOperationResultType ResultTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SVD.VDWS.VehicleType> Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.GetOperationResultType ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleType", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Models")]
    [System.SerializableAttribute()]
    public partial class VehicleType : SVD.VDWS.VdBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.ApprovalStatus ApprovalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.ApprovalStatus ApprovalStatus {
            get {
                return this.ApprovalStatusField;
            }
            set {
                if ((this.ApprovalStatusField.Equals(value) != true)) {
                    this.ApprovalStatusField = value;
                    this.RaisePropertyChanged("ApprovalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOperationResultType", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager")]
    public enum GetOperationResultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureEntityDoesntExist = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureApplicationFault = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleManufacturer", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Models")]
    [System.SerializableAttribute()]
    public partial class VehicleManufacturer : SVD.VDWS.VdBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.ApprovalStatus ApprovalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> ModelsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SVD.VDWS.VehicleType> TypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WikipediaIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.ApprovalStatus ApprovalStatus {
            get {
                return this.ApprovalStatusField;
            }
            set {
                if ((this.ApprovalStatusField.Equals(value) != true)) {
                    this.ApprovalStatusField = value;
                    this.RaisePropertyChanged("ApprovalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> Models {
            get {
                return this.ModelsField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelsField, value) != true)) {
                    this.ModelsField = value;
                    this.RaisePropertyChanged("Models");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SVD.VDWS.VehicleType> Types {
            get {
                return this.TypesField;
            }
            set {
                if ((object.ReferenceEquals(this.TypesField, value) != true)) {
                    this.TypesField = value;
                    this.RaisePropertyChanged("Types");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WikipediaId {
            get {
                return this.WikipediaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WikipediaIdField, value) != true)) {
                    this.WikipediaIdField = value;
                    this.RaisePropertyChanged("WikipediaId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VdBase", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.VehicleType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.VehicleModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.Client))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SVD.VDWS.VehicleManufacturer))]
    public partial class VdBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPersistedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPersisted {
            get {
                return this.IsPersistedField;
            }
            set {
                if ((this.IsPersistedField.Equals(value) != true)) {
                    this.IsPersistedField = value;
                    this.RaisePropertyChanged("IsPersisted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleModel", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Models")]
    [System.SerializableAttribute()]
    public partial class VehicleModel : SVD.VDWS.VdBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.ApprovalStatus ApprovalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EngineSizeCcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ManufacturerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SVD.VDWS.VehicleType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VariantNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WikipediaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YearIntroducedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YearStoppedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.ApprovalStatus ApprovalStatus {
            get {
                return this.ApprovalStatusField;
            }
            set {
                if ((this.ApprovalStatusField.Equals(value) != true)) {
                    this.ApprovalStatusField = value;
                    this.RaisePropertyChanged("ApprovalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EngineSizeCc {
            get {
                return this.EngineSizeCcField;
            }
            set {
                if ((this.EngineSizeCcField.Equals(value) != true)) {
                    this.EngineSizeCcField = value;
                    this.RaisePropertyChanged("EngineSizeCc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManufacturerId {
            get {
                return this.ManufacturerIdField;
            }
            set {
                if ((this.ManufacturerIdField.Equals(value) != true)) {
                    this.ManufacturerIdField = value;
                    this.RaisePropertyChanged("ManufacturerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SVD.VDWS.VehicleType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VariantName {
            get {
                return this.VariantNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VariantNameField, value) != true)) {
                    this.VariantNameField = value;
                    this.RaisePropertyChanged("VariantName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WikipediaId {
            get {
                return this.WikipediaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WikipediaIdField, value) != true)) {
                    this.WikipediaIdField = value;
                    this.RaisePropertyChanged("WikipediaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YearIntroduced {
            get {
                return this.YearIntroducedField;
            }
            set {
                if ((this.YearIntroducedField.Equals(value) != true)) {
                    this.YearIntroducedField = value;
                    this.RaisePropertyChanged("YearIntroduced");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YearStopped {
            get {
                return this.YearStoppedField;
            }
            set {
                if ((this.YearStoppedField.Equals(value) != true)) {
                    this.YearStoppedField = value;
                    this.RaisePropertyChanged("YearStopped");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager.Models")]
    [System.SerializableAttribute()]
    public partial class Client : SVD.VDWS.VdBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallbackUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallbackUrl {
            get {
                return this.CallbackUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.CallbackUrlField, value) != true)) {
                    this.CallbackUrlField = value;
                    this.RaisePropertyChanged("CallbackUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApprovalStatus", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager")]
    public enum ApprovalStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Suggested = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateOperationResultType", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager")]
    public enum UpdateOperationResultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureEntityAlreadyExists = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureEntityIsInvalid = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureApplicationFault = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteOperationResultType", Namespace="http://schemas.datacontract.org/2004/07/VehicleDatabaseManager")]
    public enum DeleteOperationResultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureEntityDoesntExist = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureEntityHasDependencies = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureApplicationFault = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VDWS.IVdService")]
    public interface IVdService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVdService/GetVehicleTypes", ReplyAction="http://tempuri.org/IVdService/GetVehicleTypesResponse")]
        SVD.VDWS.GetVehicleTypesResponse GetVehicleTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVdService/GetVehicleManufacturers", ReplyAction="http://tempuri.org/IVdService/GetVehicleManufacturersResponse")]
        SVD.VDWS.GetVehicleManufacturersResponse GetVehicleManufacturers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVdService/GetVehicleManufacturer", ReplyAction="http://tempuri.org/IVdService/GetVehicleManufacturerResponse")]
        SVD.VDWS.GetVehicleManufacturerResponse GetVehicleManufacturer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVdService/GetVehicleModel", ReplyAction="http://tempuri.org/IVdService/GetVehicleModelResponse")]
        SVD.VDWS.GetVehicleModelResponse GetVehicleModel(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVdService/GetVehicleModelsByManufacturerId", ReplyAction="http://tempuri.org/IVdService/GetVehicleModelsByManufacturerIdResponse")]
        SVD.VDWS.GetVehicleModelsByManufacturerIdResponse GetVehicleModelsByManufacturerId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVdService/GetVehicleModelsByManufacturer", ReplyAction="http://tempuri.org/IVdService/GetVehicleModelsByManufacturerResponse")]
        SVD.VDWS.GetVehicleModelsByManufacturerResponse GetVehicleModelsByManufacturer(SVD.VDWS.VehicleManufacturer manufacturer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVdService/UpdateVehicleType", ReplyAction="http://tempuri.org/IVdService/UpdateVehicleTypeResponse")]
        SVD.VDWS.UpdateVehicleTypeResponse UpdateVehicleType(SVD.VDWS.VehicleType type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVdService/UpdateVehicleManufacturer", ReplyAction="http://tempuri.org/IVdService/UpdateVehicleManufacturerResponse")]
        SVD.VDWS.UpdateVehicleManufacturerResponse UpdateVehicleManufacturer(SVD.VDWS.VehicleManufacturer manufacturer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVdService/UpdateVehicleModel", ReplyAction="http://tempuri.org/IVdService/UpdateVehicleModelResponse")]
        SVD.VDWS.UpdateVehicleModelResponse UpdateVehicleModel(SVD.VDWS.VehicleModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVdService/UpdateClient", ReplyAction="http://tempuri.org/IVdService/UpdateClientResponse")]
        SVD.VDWS.UpdateClientResponse UpdateClient(SVD.VDWS.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVdService/DeleteVehicleType", ReplyAction="http://tempuri.org/IVdService/DeleteVehicleTypeResponse")]
        SVD.VDWS.DeleteVehicleTypeResponse DeleteVehicleType(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVdService/DeleteVehicleManufacturer", ReplyAction="http://tempuri.org/IVdService/DeleteVehicleManufacturerResponse")]
        SVD.VDWS.DeleteVehicleTypeResponse DeleteVehicleManufacturer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVdService/DeleteVehicleModel", ReplyAction="http://tempuri.org/IVdService/DeleteVehicleModelResponse")]
        SVD.VDWS.DeleteVehicleModelResponse DeleteVehicleModel(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVdService/DeleteClient", ReplyAction="http://tempuri.org/IVdService/DeleteClientResponse")]
        SVD.VDWS.DeleteClientResponse DeleteClient(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVdServiceChannel : SVD.VDWS.IVdService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VdServiceClient : System.ServiceModel.ClientBase<SVD.VDWS.IVdService>, SVD.VDWS.IVdService {
        
        public VdServiceClient() {
        }
        
        public VdServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VdServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VdServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VdServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SVD.VDWS.GetVehicleTypesResponse GetVehicleTypes() {
            return base.Channel.GetVehicleTypes();
        }
        
        public SVD.VDWS.GetVehicleManufacturersResponse GetVehicleManufacturers() {
            return base.Channel.GetVehicleManufacturers();
        }
        
        public SVD.VDWS.GetVehicleManufacturerResponse GetVehicleManufacturer(int id) {
            return base.Channel.GetVehicleManufacturer(id);
        }
        
        public SVD.VDWS.GetVehicleModelResponse GetVehicleModel(int id) {
            return base.Channel.GetVehicleModel(id);
        }
        
        public SVD.VDWS.GetVehicleModelsByManufacturerIdResponse GetVehicleModelsByManufacturerId(int id) {
            return base.Channel.GetVehicleModelsByManufacturerId(id);
        }
        
        public SVD.VDWS.GetVehicleModelsByManufacturerResponse GetVehicleModelsByManufacturer(SVD.VDWS.VehicleManufacturer manufacturer) {
            return base.Channel.GetVehicleModelsByManufacturer(manufacturer);
        }
        
        public SVD.VDWS.UpdateVehicleTypeResponse UpdateVehicleType(SVD.VDWS.VehicleType type) {
            return base.Channel.UpdateVehicleType(type);
        }
        
        public SVD.VDWS.UpdateVehicleManufacturerResponse UpdateVehicleManufacturer(SVD.VDWS.VehicleManufacturer manufacturer) {
            return base.Channel.UpdateVehicleManufacturer(manufacturer);
        }
        
        public SVD.VDWS.UpdateVehicleModelResponse UpdateVehicleModel(SVD.VDWS.VehicleModel model) {
            return base.Channel.UpdateVehicleModel(model);
        }
        
        public SVD.VDWS.UpdateClientResponse UpdateClient(SVD.VDWS.Client client) {
            return base.Channel.UpdateClient(client);
        }
        
        public SVD.VDWS.DeleteVehicleTypeResponse DeleteVehicleType(int id) {
            return base.Channel.DeleteVehicleType(id);
        }
        
        public SVD.VDWS.DeleteVehicleTypeResponse DeleteVehicleManufacturer(int id) {
            return base.Channel.DeleteVehicleManufacturer(id);
        }
        
        public SVD.VDWS.DeleteVehicleModelResponse DeleteVehicleModel(int id) {
            return base.Channel.DeleteVehicleModel(id);
        }
        
        public SVD.VDWS.DeleteClientResponse DeleteClient(int id) {
            return base.Channel.DeleteClient(id);
        }
    }
}
