ALTER TABLE [dbo].[VehicleLocations]
    ADD CONSTRAINT [PK_VehicleLocations] PRIMARY KEY CLUSTERED ([VehicleID] ASC, [LocationID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

